const sounds = [
	{ filename: 'eugh1', source: 'Season 1', displayName: 'Eugh #1' },
	{ filename: 'eugh2', source: 'Season 1', displayName: 'Eugh #2' },
	{ filename: 'eugh3', source: 'Season 1', displayName: 'Eugh #3' },
	{ filename: 'eugh4', source: 'Season 1', displayName: 'Eugh #4' },
	{ filename: 'explosion', source: 'Season 1', displayName: 'Explosion!' },
	{ filename: 'hyoizaburo', source: 'Season 1', displayName: 'Hyoizaburo!' },
	{ filename: 'itai', source: 'Season 1', displayName: '痛い!' },
	{ filename: 'kazuma', source: 'Season 1', displayName: 'Kazuma' },
	{ filename: 'magic-item', source: 'Season 1', displayName: 'Magic Item' },
	{ filename: 'n', source: 'Season 1', displayName: '\'n!' },
	{ filename: 'name', source: 'Season 1', displayName: 'My Name is..' },
	{ filename: 'oi', source: 'Season 1', displayName: 'Oi' },
	{ filename: 'parents', source: 'Season 1', displayName: 'Parents' },
	{ filename: 'plosion', source: 'Season 1', displayName: '\'plosion!' },
	{ filename: 'pull', source: 'Season 1', displayName: 'Eyepatch-Pull' },
	{ filename: 'sion', source: 'Season 1', displayName: '\'sion!' },
	{ filename: 'star', source: 'Season 1', displayName: 'Star entry' },
	{ filename: 'yamero', source: 'Season 1', displayName: 'やめろ!!' },

	{ filename: 'are', source: 'Season 2', displayName: 'Are?' },
	{ filename: 'aughh', source: 'Season 2', displayName: 'Aughh' },
	{ filename: 'bighug', source: 'Season 2', displayName: 'Big Hug' },
	{ filename: 'chomusuke', source: 'Season 2', displayName: 'Chomusuke' },
	{ filename: 'chomusukefaint', source: 'Season 2', displayName: 'Chomu Faint' },
	{ filename: 'chunchunmaru', source: 'Season 2', displayName: 'Chunchunmaru' },
	{ filename: 'comeatme', source: 'Season 2', displayName: 'Come at me!' },
	{ filename: 'dododo', source: 'Season 2', displayName: 'Dododo' },
	{ filename: 'dontwanna', source: 'Season 2', displayName: 'Don\'t wanna' },
	{ filename: 'doushimashou', source: 'Season 2', displayName: 'どうしましょう' },
	{ filename: 'explosion2', source: 'Season 2', displayName: 'Explosion! 2' },
	{ filename: 'friends', source: 'Season 2', displayName: 'Friends' },
	{ filename: 'hau', source: 'Season 2', displayName: 'Hau' },
	{ filename: 'hmph', source: 'Season 2', displayName: 'Hmph' },
	{ filename: 'hua', source: 'Season 2', displayName: 'Hua' },
	{ filename: 'igiari', source: 'Season 2', displayName: '異議あり!!' },
	{ filename: 'isee', source: 'Season 2', displayName: 'I see' },
	{ filename: 'itscold', source: 'Season 2', displayName: 'It\'s cold' },
	{ filename: 'ladiesfirst', source: 'Season 2', displayName: 'Ladies first' },
	{ filename: 'lalala', source: 'Season 2', displayName: '♬Explosions♬' },
	{ filename: 'losion', source: 'Season 2', displayName: '\'losion!' },
	{ filename: 'mywin', source: 'Season 2', displayName: 'My Win!' },
	{ filename: 'n2', source: 'Season 2', displayName: '\'n! 2' },
	{ filename: 'nani', source: 'Season 2', displayName: 'Nani?!' },
	{ filename: 'oh', source: 'Season 2', displayName: 'Oh' },
	{ filename: 'ripchomusuke', source: 'Season 2', displayName: 'RIP Chomu' },
	{ filename: 'shouganai', source: 'Season 2', displayName: 'しょうがない' },
	{ filename: 'sigh', source: 'Season 2', displayName: 'Sigh' },
	{ filename: 'sion2', source: 'Season 2', displayName: '\'sion! 2' },
	{ filename: 'splat', source: 'Season 2', displayName: '*splat*' },
	{ filename: 'thinking', source: 'Season 2', displayName: 'Thinking' },
	{ filename: 'tropes', source: 'Season 2', displayName: 'Tropes' },
	{ filename: 'truepower', source: 'Season 2', displayName: 'True Power' },
	{ filename: 'waah', source: 'Season 2', displayName: 'Waah!' },
	{ filename: 'wellthanks', source: 'Season 2', displayName: 'Well, thanks' },
	{ filename: 'whatsthis', source: 'Season 2', displayName: 'What\'s this?!' },
	{ filename: 'who', source: 'Season 2', displayName: 'Who..?' },
	{ filename: 'yes', source: 'Season 2', displayName: 'Yes' },
	{ filename: 'yoroshii', source: 'Season 2', displayName: 'よろしい' },
	{ filename: 'zuryah', source: 'Season 2', displayName: 'Zuryah!!' },

	{ filename: 'realname', source: '', displayName: '' },
];

if (typeof process === 'object') module.exports = sounds;