const sounds = [
	{ filename: 'eugh1', season: '1', displayName: 'Eugh #1' },
	{ filename: 'eugh2', season: '1', displayName: 'Eugh #2' },
	{ filename: 'eugh3', season: '1', displayName: 'Eugh #3' },
	{ filename: 'eugh4', season: '1', displayName: 'Eugh #4' },
	{ filename: 'explosion', season: '1', displayName: 'Explosion!' },
	{ filename: 'hyoizaburo', season: '1', displayName: 'Hyoizaburo!' },
	{ filename: 'itai', season: '1', displayName: '痛い!' },
	{ filename: 'magic-item', season: '1', displayName: 'Magic Item' },
	{ filename: 'n', season: '1', displayName: '\'n!' },
	{ filename: 'name', season: '1', displayName: 'My Name is..' },
	{ filename: 'oi', season: '1', displayName: 'Oi' },
	{ filename: 'parents', season: '1', displayName: 'Parents' },
	{ filename: 'plosion', season: '1', displayName: '\'plosion!' },
	{ filename: 'pull', season: '1', displayName: 'Eyepatch-Pull' },
	{ filename: 'sion', season: '1', displayName: '\'sion!' },
	{ filename: 'star', season: '1', displayName: 'Star entry' },
	{ filename: 'yamero', season: '1', displayName: 'やめろ!!' },

	{ filename: 'are', season: '2', displayName: 'Are?' },
	{ filename: 'aughh', season: '2', displayName: 'Aughh' },
	{ filename: 'bighug', season: '2', displayName: 'Big Hug' },
	{ filename: 'chomusuke', season: '2', displayName: 'Chomusuke' },
	{ filename: 'chomusukefaint', season: '2', displayName: 'Chomu Faint' },
	{ filename: 'chunchunmaru', season: '2', displayName: 'Chunchunmaru' },
	{ filename: 'comeatme', season: '2', displayName: 'Come at me!' },
	{ filename: 'dododo', season: '2', displayName: 'Dododo' },
	{ filename: 'dontwanna', season: '2', displayName: 'Don\'t wanna' },
	{ filename: 'doushimashou', season: '2', displayName: 'どうしましょう' },
	{ filename: 'explosion2', season: '2', displayName: 'Explosion! 2' },
	{ filename: 'friends', season: '2', displayName: 'Friends' },
	{ filename: 'hau', season: '2', displayName: 'Hau' },
	{ filename: 'hmph', season: '2', displayName: 'Hmph' },
	{ filename: 'hua', season: '2', displayName: 'Hua' },
	{ filename: 'igiari', season: '2', displayName: '異議あり!!' },
	{ filename: 'isee', season: '2', displayName: 'I see' },
	{ filename: 'itscold', season: '2', displayName: 'It\'s cold' },
	{ filename: 'ladiesfirst', season: '2', displayName: 'Ladies first' },
	{ filename: 'lalala', season: '2', displayName: '♬Explosions♬' },
	{ filename: 'losion', season: '2', displayName: '\'losion!' },
	{ filename: 'mywin', season: '2', displayName: 'My Win!' },
	{ filename: 'n2', season: '2', displayName: '\'n! 2' },
	{ filename: 'nani', season: '2', displayName: 'Nani?!' },
	{ filename: 'oh', season: '2', displayName: 'Oh' },
	{ filename: 'ripchomusuke', season: '2', displayName: 'RIP Chomu' },
	{ filename: 'shouganai', season: '2', displayName: 'しょうがない' },
	{ filename: 'sigh', season: '2', displayName: 'Sigh' },
	{ filename: 'sion2', season: '2', displayName: '\'sion! 2' },
	{ filename: 'splat', season: '2', displayName: '*splat*' },
	{ filename: 'thinking', season: '2', displayName: 'Thinking' },
	{ filename: 'tropes', season: '2', displayName: 'Tropes' },
	{ filename: 'truepower', season: '2', displayName: 'True Power' },
	{ filename: 'waah', season: '2', displayName: 'Waah!' },
	{ filename: 'wellthanks', season: '2', displayName: 'Well, thanks' },
	{ filename: 'whatsthis', season: '2', displayName: 'What\'s this?!' },
	{ filename: 'who', season: '2', displayName: 'Who..?' },
	{ filename: 'yes', season: '2', displayName: 'Yes' },
	{ filename: 'yoroshii', season: '2', displayName: 'よろしい' },
	{ filename: 'zuryah', season: '2', displayName: 'Zuryah!!' },

	{ filename: 'realname', season: '', displayName: '' },
];

if (typeof process === 'object') module.exports = sounds;